development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://yzzvolnvuewoby:97552bfbe715d0edfc5969762991f749dc3318d996821b63ac73530656dba4ac@ec2-23-21-201-12.compute-1.amazonaws.com:5432/dfon2m4bi6n6ta
  channel_prefix: nameofapp_production


  # url: redis://localhost:6379/1